theme: jekyll-theme-slate
title: Bayesian Analysis of the Bechdel Test
# --- Navigation bar options --- #

navbar:
  title: "Bayesian Analysis"
  left:
    - text: "Home"
      href: index.html
    - text: "Data Cleaning and Exploration: R Code"
      href: data_cleaning_r.html
    - text: "Data Cleaning: Python Code"
      href: data_cleaning_python.html
    - text: "Bayesian Models: R Code"
      href: models_r.html
